name: Python CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**-init'
      - '**-conf'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --quiet -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install --quiet flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # the GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    # installing only after lint saves about 30s if the lint was going to fail
    - name: Install test dependencies
      run: |
        sudo apt install -y -qq whois

    - name: Run
      run: |
        echo " * ./microwhoisd.py"
        ./microwhoisd.py --config config-dist.yaml --listen 127.0.0.1 --port 4343 &
        listening=false
        for i in {1..10}; do ss -ltpn '( sport = :4343 )' | grep :4343 && listening=true && break; sleep 1; done
        if $listening ; then
        echo " * whois"
        whois --host 127.0.0.1 --port 4343 192.168.1.1
        else
        echo "./microwhoisd.py did not start listening"
        fi
        echo " * check daemon"
        jobs %% && : make sure the daemon did not die
        kill -term %%
