name: Python CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**-init'
      - '**-conf'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, '3.9.0-beta.5 - 3.9']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --quiet -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install --quiet flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # the GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    # installing only after lint saves about 30s if the lint was going to fail
    - name: Install test dependencies
      run: |
        sudo apt install -y -qq whois

    - name: Run
      run: |
        /usr/bin/env python3 --version
        echo " * ./microwhoisd.py"
        timeout --kill-after=5s 15s \
        ./microwhoisd.py --config config-dist.yaml --listen 127.0.0.1 --port 4343 &
        listening=false
        for i in {1..100}; do ss -ltpn '( sport = :4343 )' | grep :4343 && listening=true && break; sleep .1; done
        if $listening ; then
        echo " * whois"
        whois --host 127.0.0.1 --port 4343 192.168.1.1
        else
        echo "./microwhoisd.py did not start listening"
        fi
        echo " * check daemon still running"
        jobs %%
        jobs %% | grep Running
        kill -term %%
        $listening # fail if it never started listening
